steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/snake-game-repo/snake-game:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/snake-game-repo/snake-game:$SHORT_SHA'

  - name: 'docker.io/aquasec/trivy'
    args:
      - 'image'
      - '--exit-code'
      - '0'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/snake-game-repo/snake-game:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=snake-game-cluster'
    args:
      - 'apply'
      - '-f'
      - 'k8s-deployment.yaml'

  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=snake-game-cluster'
    args:
      - 'set'
      - 'image'
      - 'deployment/snake-game-deployment'
      - 'snake-game=us-central1-docker.pkg.dev/$PROJECT_ID/snake-game-repo/snake-game:$SHORT_SHA'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/snake-game-repo/snake-game:$SHORT_SHA'
