apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-game-deployment
  labels:
    app: snake-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-game
  template:
    metadata:
      labels:
        app: snake-game
    spec:
      containers:
      - name: snake-game
        image: us-central1-docker.pkg.dev/ratik-454322/snake-game-repo/snake-game:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: snake-game-service
spec:
  type: LoadBalancer
  selector:
    app: snake-game
  ports:
    - port: 80
      targetPort: 8080
